server:
  port: 8080

spring:
  mvc:
    servlet:
      path: /api
  datasource:
    url: jdbc:h2:mem:blog;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  elasticsearch:
    host: localhost:9200
    uris: http://localhost:9200
    username: elastic
    password: changeme
    repositories:
      enabled: true

springdoc:
  api-docs.path: /v3/api-doc
  swagger-ui.path: /swagger-ui
application-description: '@project.description@'
application-version: '@project.version@'
